name: braintraining2
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.7+1
  fluttertoast: ^4.0.1
  flutter_auth_buttons: ^0.8.0
  countdown: ^0.1.0
  
  maps_launcher: ^1.2.0
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.4.5

  cupertino_icons: ^0.1.3
  flutter_speed_dial: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icon/
    

  

  